development:
  adapter: postgresql
  encoding: unicode 
  host: localhost
  database: mbkmrk 
  pool: 5
  username: 
  password: 

test:
  adapter: postgresql
  encoding: unicode
  host: localhost
  database: mbkmrk 
  pool: 5
  username: 
  password: 

